require:
  - rubocop-performance
  - rubocop-sketchup

inherit_from: sketchup-style.yml

AllCops:
  # RuboCop 1.x uses semantic versioning. However, to avoid the CI build from
  # breaking when a new cop is added that might yield warnings new cops are
  # kept disabled and instead enabled explicitly as new versions are tested.
  # NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'examples/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true


# Need to explicitly disable the SketchUp cops here because Rake tasks will
# load the gem and cause them to be run.
# (Not sure why DisabledByDefault isn't enough.)

SketchupBugs:
  Enabled: false

SketchupDeprecations:
  Enabled: false

SketchupPerformance:
  Enabled: false

SketchupRequirements:
  Enabled: false

SketchupSuggestions:
  Enabled: false


Gemspec/DateAssignment: # new in 1.10
  Enabled: true


Layout/ArrayAlignment:
  Exclude:
    - spec/**/*

Layout/AssignmentIndentation:
  Exclude:
    - tasks/cops_documentation.rake

Layout/BeginEndAlignment: # (new in 0.91)
  Enabled: true

Layout/FirstArgumentIndentation:
  Exclude:
    - tasks/**/*

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: true

Layout/LineLength:
  Max: 80
  Exclude:
    - lib/rubocop/sketchup/cop/suggestions/operation_name.rb
    - spec/**/*
    - tasks/**/*
    - tools/**/*

Layout/IndentationConsistency:
  Exclude:
    - spec/**/*

Layout/ParameterAlignment:
  Exclude:
    - spec/**/*
    - tasks/**/*

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: true


Lint/AmbiguousAssignment: # new in 1.7
  Enabled: true

Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true

Lint/AmbiguousRange: # new in 1.19
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/BooleanSymbol:
  Exclude:
    - lib/rubocop/sketchup/cop/deprecations/operation_next_transparent.rb

Lint/ConstantDefinitionInBlock: # (new in 0.91)
  Enabled: true
  Exclude:
    - spec/**/*

Lint/DeprecatedConstants: # new in 1.8
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateBranch: # new in 1.3
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: true

Lint/DuplicateRequire: # (new in 0.90)
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyBlock: # new in 1.1
  Enabled: true

Lint/EmptyClass: # new in 1.3
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile: # (new in 0.90)
  Enabled: true

Lint/EmptyInPattern: # new in 1.16
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/HashCompareByIdentity: # (new in 0.93)
  Enabled: true

Lint/IdentityComparison: # (new in 0.91)
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true

Lint/InterpolationCheck:
  Exclude:
    - spec/rubocop/sketchup/cop/requirements/observers_start_operation_spec.rb

Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: true

Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: true

Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: true

Lint/RedundantSafeNavigation: # (new in 0.93)
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/SymbolConversion: # new in 1.9
  Enabled: true

Lint/ToEnumArguments: # new in 1.1
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration: # (new in 0.90)
  Enabled: true

Lint/TripleQuotes: # new in 1.9
  Enabled: true

Lint/UnexpectedBlockArity: # new in 1.5
  Enabled: true

Lint/UnmodifiedReduceAccumulator: # new in 1.1
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessMethodDefinition: # (new in 0.90)
  Enabled: true

Lint/UselessTimes: # (new in 0.91)
  Enabled: true


Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - tasks/cops_documentation.rake
    - tasks/cut_release.rake
    - tools/stdlib_scraper.rb

Metrics/ClassLength:
  Exclude:
    - lib/rubocop/sketchup/cop/requirements/ruby_core_namespace.rb
    - lib/rubocop/sketchup/cop/requirements/ruby_stdlib_namespace.rb
    - lib/rubocop/sketchup/formatter/extension_review.rb
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - lib/rubocop/sketchup/cop/requirements/file_structure.rb
    - lib/rubocop/sketchup/cop/requirements/sketchup_extension.rb
    - tasks/**/*
    - spec/**/*

Metrics/ModuleLength:
  Exclude:
    - lib/rubocop/sketchup/dc_methods.rb
    - lib/rubocop/sketchup/features.rb


Naming/FileName:
  Exclude:
    - lib/rubocop-sketchup.rb # Not changing the name now.


# When performance isn't critical, computing sizes avoid magic numbers that
# might get out of sync.
Performance/FixedSize:
  Exclude:
    - tasks/cops_documentation.rake

# What this cop suggests makes the code less intuitive/readable.
# Keeping it disabled until there's a known tangible performance impact for this
# gem.
Performance/UnfreezeString:
  Enabled: false

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true


Style/AccessorGrouping:
  Enabled: true

Style/ArgumentsForwarding: # new in 1.1
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ClassEqualityComparison: # (new in 0.93)
  Enabled: true

Style/ClassVars:
  Exclude:
    - lib/rubocop/sketchup/cop/requirements/extension_namespace.rb
    - lib/rubocop/sketchup/cop/requirements/file_structure.rb

Style/CollectionCompact: # new in 1.2
  Enabled: true

Style/CombinableLoops: # (new in 0.90)
  Enabled: true

Style/DocumentDynamicEvalDefinition: # new in 1.1
  Enabled: true

Style/EndlessMethod: # new in 1.8
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashConversion: # new in 1.10
  Enabled: true

Style/HashExcept: # new in 1.7
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/IfWithBooleanLiteralBranches: # new in 1.9
  Enabled: true

Style/InPatternThen: # new in 1.16
  Enabled: true

Style/KeywordParametersOrder: # (new in 0.90)
  Enabled: true

Style/MultilineBlockChain:
  Exclude:
    - lib/rubocop/sketchup/formatter/extension_review.rb

Style/MultilineInPatternThen: # new in 1.16
  Enabled: true

Style/NegatedIfElseCondition: # new in 1.2
  Enabled: true

Style/NilLambda: # new in 1.3
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/QuotedSymbols: # new in 1.16
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantSelfAssignment: # (new in 0.90)
  Enabled: true

Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: true

Style/SafeNavigation:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/SoleNestedConditional: # (new in 0.90)
  Enabled: true

Style/StringChars: # new in 1.12
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/SwapValues: # new in 1.1
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  Exclude:
    - spec/**/*
    - tasks/cops_documentation.rake
