site_name: "RuboCop SketchUp: SketchUp Extension Best Practices"
repo_url: https://github.com/sketchup/rubocop-sketchup
edit_uri: edit/main/manual/
copyright: "Copyright &copy; 2017-2021 Trimble Inc. SketchUp and contributors"
docs_dir: manual
nav:
  - Home: index.md
  - Installation: installation.md
  - Basic Usage: basic_usage.md
  - Cops: cops.md
  - Formatters: formatters.md
  - Configuration: configuration.md
  - Integration with other tools: integration_with_other_tools.md
  - Contributing: contributing.md
  - Development: development.md
  - Cops Documentation:
    - Requirements Cops: cops_requirements.md
    - Deprecations Cops: cops_deprecations.md
    - Performance Cops: cops_performance.md
    - Suggestions Cops: cops_suggestions.md
    - Bugs Cops: cops_bugs.md
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
theme: readthedocs
